README.md

As per https://github.com/Sriparno08/Openpedia/issues/66
Added balenaCloud Docs github page to list
Added balenaCloud Docs github page to list in specified category
- [x ] Beginner-Friendly Repositories
[]
Fixes #66 
- [x ] The name of the resource is correctly spelled (if applicable)
- [x ] The link to the resource is working (if applicable)

Add balenaCloud Docs

---

CONTRIBUTING.md

 The diff is changing the resource type "YouTube Video" to "Video".

---

client/faq/index.html

Removed Notification From the FAQ Page
Fixes #151

Removed Notification From the FAQ Page

---

client/styles.css

Add Margin to Social Links in the footer of the landing page.
- Fixes #222

[ISSUE - 222] Add Margin to Social Links

---

client/styles.css

changed the font size of the landing page copyright text from 13px to 16px:
Fixes #219

UI: Change Font Size of Copyright Text Updated

---

client/index.html

I removed the FAQ button in the landing page as a contribution under JWOC'24
Fixes #306

Removed FAQ from landing page

---

client/Introduction-opensource/index.html
client/index.html

I removed the FAQ from introduction to Opensource page navbar and made a contribution as a part of JWOC'24
Fixes #307

Removed the FAQ from introduction to Opensource page navbar

---

client/Introduction-opensource/index.html
client/git/index.html

I removed the about button from learn Git & Github page as a contribution under JWOC'24
Fixes #314

Removed about button from Learn Git & Github page

---

client/index.html

I've removed the Twitter icon from the footer as requested . 
Fixes #352

Remove Twitter icon from footer

---

client/src/theme/theme_switch.css

Changed the border color for dark mode for button Get Started.
Fixes #344 
**Working under JWOC**

Update border color for 'Get Started' button in dark mode

---

client/components/footer.js

Changed <a href="https://openpedia.netlify.app/contributing%20to%20opensource/" class="footer-links">Contributing to Open Source</a> to <a href="./pages/contributing-to-open-source/index.html" class="footer-links">Contributing to Open Source</a> in footer.js
Fixes #384
- [x ] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ x] The name of the resource is spelled correctly (if applicable)
- [ x] The link to the resource is working (if applicable)

Footer.js Broken link FIX

---

client/pages/learn-git-and-github/index.html

Updated SVG link path in file client/pages/learn-git-and-github/index.html
- [ x] Codebase
Fixes #392 
- [ x] The name of the resource is spelled correctly (if applicable)
- [x ] The link to the resource is working (if applicable)
- [x ] The resource is added in the correct format (if applicable)

Chore: Fix SVG Link in 'Learn Git & GitHub' Page

---

client/pages/contributing-to-open-source/index.html

Updated icon path in "contributing to open source" page
- [x ] Codebase
Fixes #393 
- [ x] The name of the resource is spelled correctly (if applicable)
- [ x] The link to the resource is working (if applicable)

Chore: Fix SVG Link in 'Contributing to Open Source' Page

---

client/pages/beginner-friendly-repos/index.html

Fixed SVG Link in 'Beginner-Friendly Repos' Page
Fixes #394

Chore: Fix SVG Link in 'Beginner-Friendly Repos' Page

---

client/components/footer.js

old: ./opensource_programs/index.html
new: ./pages/open-source-programs/index.html
Chore: Fix 'Open Source Programs' Link in Landing Page Footer #386
We need to fix a broken link in the landing page footer that heads to the 'Open Source Programs' page.
Step 1: Go to client/components/footer.js
Step 2: Find the following link under <div class="col">...</div>
<a href="./opensource_programs/index.html" class="footer-links">Open Source Programs</a>
Step 3: Change it to
<a href="./pages/open-source-programs/index.html" class="footer-links">Open Source Programs</a>
Exactly what I fixed.
Fixes #386

updated the anker with a new Hyper-Reference

---

client/index.html

I changed the broken link for 'Learn Git & GitHub' in the category section to the correct link.
Fixes #379

Fix broken link for Learn Git & Github category

---

client/index.html

I changed the broken link for 'Introduction to Open Source' in the category section to the correct link.
Fixes #378

Chore: Fix 'Introduction to Open Source' Link in 'Categories' Section

---

client/pages/introduction-to-open-source/index.html

Replaced  ```<link rel="icon" href="./assets/short-logo.svg">``` 
in  ```client/pages/introduction-to-open-source/index.html```
with ```<link rel="icon" href="../../assets/short-logo.jpg">```.
Fixes #391

fixed broken SVG link in the 'Introduction to Open Source' page.

---

client/components/footer.js

I fixed 'Beginner-Friendly Repos' Link in Landing Page Footer
Fixes #385

Fixed 'Beginner-Friendly Repos' Link in Landing Page Footer

---

client/components/footer.js

Added Hover Effect to 'Documentation' in Landing Page Footer 
Fixes #420

issue #420 fixed

---

client/pages/beginner-friendly-repos/app.js
client/pages/beginner-friendly-repos/styles.css

Fixed the colors of the cards to improve the readable in dark mode. In doing so, I adjusted the colors to match the style of the other pages. Also, I added buttons for "Read more" in the same style as on other pages.  
Dark mode:  
Light mode:  
Dark mode:  
Light mode:  
Fixes #543

[UI] Fix dark mode on page beginner friendly repos
