Sriparno08/Openpedia

CONTRIBUTING.md

Improved the description of the 'Pull Requests' section in CONTRIBUTING.md.
Closes #6

Improve 'Pull Requests' Description in CONTRIBUTING.md

---

CONTRIBUTING.md

Merged steps in CONTRIBUTING.md file

---

.gihub/PULL_REQUEST_TEMPLATE.md

- refer https://github.com/Sriparno08/Start-Contributing/issues/10
- added pr template

Add PR Template

---

README.md

Added description under open source programs.

 Description Added.

---

README.md

Adding the category 'Beginner-Friendly Repositories' to the README.md file and create the first link.
- [MDN Web Docs](https://github.com/mdn/content)

Add 'Beginner-Friendly Repositories' section to the README.md from ConstiCode

---

README.md

Add MindsDB to 'Beginner-Friendly Repositories'

---

CONTRIBUTING.md

Update style guide

---

README.md

Hello @Sriparno08,
I added description for beginner friendly repositories. Please have a look.
Related to #25 
Regards,
Suraj Khamkar

Description for Beginner friendly repo

---

README.md

- Need to add the Github docs for the reference.
*Describe your changes here*
-  Added Github Docs link to the ReadMe Doc in the Beginner friendly Repositories sections.
#23

Add Github Docs

---

README.md

Need to add BioDrop for the reference.
*Describe your changes here*
- Added BioDrop link to the ReadMe Doc in the Beginner friendly Repositories sections.
#33

Add BioDrop

---

.github/PULL_REQUEST_TEMPLATE.md

Added one more category and changed the description of 'Category' in PULL_REQUEST_TEMPLATE.md
#37

Changed 'Category' in PR template

---

.github/PULL_REQUEST_TEMPLATE.md

Changed the content under the 'Checklist' in the file PULL_REQUEST_TEMPLATE.md to the suggested content mentioned in the open issue https://github.com/Sriparno08/Start-Contributing/issues/39 to make my first ever contribution.
#39

Updated the content under 'Checklist' in PULL_REQUEST_TEMPLATE.md

---

.github/PULL_REQUEST_TEMPLATE.md

Changed the markdown with the suggested description text mentioned in the issue
*Describe your changes here*
Fixes #XX

Update PULL_REQUEST_TEMPLATE.md with suggested markdown

---

README.md

Added bootstrap section under Beginner Friendly Repos
Fixes #XX

Update README with Bootstrap link

---

CONTRIBUTING.md

Updated the documentation in Contributing.md with the suggested mark down.
Fixes #XX

updated documentation in Contributing.md

---

README.md

Added Docusaurus link to the Beginner-Friendly Repositories section.
Fixes #54

Add Docusaurus

---

README.md

Added Storybook under 'Beginner-Friendly Repositories' in README.md.
Fixes #57

Add Storybook

---

README.md

Added 'Apache Arrow' under 'Beginner-Friendly Repositories' in README.md.
Fixes #58

Add Apache Arrow

---

README.md

Added React Native under the 'Beginner-Friendly Repositories' section in README.md.
issue#71 
Fixes #71

Add React Native

---

README.md

Added Novu under 'Beginner-Friendly Repositories'
.
Fixes #73

added Novu to the readme.md file

---

README.md

I added  Prettier under 'Beginner-Friendly Repositories'.
Fixes #63

Add prettier in readme

---

README.md

FIXED #76 
- [ x] Beginner-Friendly Repos
#76
Fixes #XX
- [x ] The resource is added in the correct format (if applicable)

Update the 'Beginner-Friendly Repos' Description #76 FIXED

---

README.md

Replaced the "introduction to open source" description in readme.md
Fixes #81

docs: updated the introduction to open source description in readme.md

---

CONTRIBUTING.md

Added "Style Guide For Pull Request" Section in CONTRIBUTING.md file
Fixes #84

Docs: Added Style Guide For Pull Request In CONTRIBUTING.md file

---

README.md

Docs: Update description under 'Learn Git and GitHub' in README.md

---

README.md

The readme document was updated according to the new suggestion.
Fixes #87

docs : update README document

---

README.md

Update 'Beginner-Friendly Repos' description

---

README.md

Updated the description of the category 'Open Source Programs' according to the issue.
Fixes #93

Docs: Update 'Open Source Programs' description in README.md

---

client/styles.css

text alignment changed to left on smaller devices of about and contribute description section

---

README.md
client/styles.css

Changing the button colors, of *Get Started* in the first section and *More* in the categories section to match the color theme of the website.
Fixes #95

UI: Change Background Color of Landing Page Buttons

---

README.md

edit readme fixed : #99

---

CONTRIBUTING.md

The readme document was updated according to the new suggestion.
Fixes #101

docs : update CONTRIBUTING.md

---

README.md

I'm adding a 'Tech Stack' section under the 'Table of Contents' section in the Readme.md file to provide users and contributors with information about the technologies used in this project. This section includes a list of technologies, frameworks, and tools utilized. I followed the existing formatting guidelines in the README.md file for consistency.
Fixes #106

Docs: Add Tech Stack Under Table of Contents in README.md

---

client/faq/index.html
client/faq/script.js
client/faq/style.css
client/index.html

Adding a comprehensive FAQ page to the project. I've ensured that the page is complete, responsive, and adheres to the project's theme.
- Fixes #132 
I have attached screenshots of the FAQ page to provide a visual representation of the changes. Feel free to review and provide feedback.
I have thoroughly tested the functionality and appearance of the FAQ page to ensure a smooth user experience. If there are any specific areas that require attention or if you have additional feedback, please let me know.

[ISSUE-132] Add FAQ Page: Complete, Responsive, and Themed

---

client/index.html

- [ x] User Interface
Fixes #128 
- [x ] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide

Chore: Change Footer Text in Landing Page #128

---

README.md
client/index.html
client/styles.css

I have added some animation styles to the links in the Navbar as well as the Get Started button, in order to make the UI more attractive and appealing. 
I have implemented a simple animation for the Get Started button to expand by 15% on hover, since the Page is mostly static and this hover effect will make the button more dynamic and engaging.
For the "About" and "GitHub" links, I added a 3D effect to each link by translating the link horizontally when hovered.
I converted the "Openpedia" title into a link directed back to the Landing page (in this case the same page), and added a CSS Transformation effect to expand the title font from 20px to 23px on detecting a mouse hover. The title shrinks back to its original size when the mouse is removed.
P.S: The reason for converting the title …

Added Animation Styles to Navbar and Get Start Button

---

client/index.html

I have removed the notification from landing page
Fixes #114

Changes in UI

---

client/index.html

This PR changes the 'About' Description in Landing Page #126
Fixes #126

Sanskritisahu21 change 'about' description in landing page #126

---

client/index.html
client/opensource_programs/index.html
client/opensource_programs/style.css

Created a new page for Details of all popular Open-Source programs. 
Fixes #131
- [] The name of the resource is spelled correctly (if applicable)

Added Open-Source Program page

---

client/index.html

Adding my name to the contributor list by changing the description of the 'Contribute' section on the landing page.
Fixes #127

Changed the 'Contribute' section description. 

---

client/opensource_programs/style.css

Padding change from 20px to 0 3rem is done in the section of Open Source programs.
Fixes #156

padding change done

---

client/opensource_programs/index.html

fix Type error in open source programs from MLG to MLH
Fixes #155

fix Type error in open source programs from MLG to MLH

---

client/faq/index.html

Change the Footer Text in FAQ Page

---

client/faq/index.html

Fix UI for the FAQ Page Navbar.
Fixes #152

Fix UI for the FAQ Page Navbar

---

client/index.html
client/styles.css

Footer section is added using html and little css
Fixes #115 
Fixes #XX

#115 Footer section is added

---

client/styles.css

This pull request addresses a change in the padding of the landing page footer section.
- [ x ] User Interface
Fixes #176
- [ x ] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ x ] The name of the resource is spelled correctly (if applicable)
- [ x ] The link to the resource is working (if applicable)
- [ x ] The resource is added in the correct format (if applicable)
- [ x ] I have tested changes on my local computer (if applicable)

UI: Add Padding in Landing Page Footer

---

client/index.html
client/styles.css

Footer section data is formatted.
Span with class creator is divided into two spans with class names copyright and creator.
New span with class copyright is given css.
The spans are aligned using flex with justify-content : space-between.
Fixes #172

UI: Format Data in Landing Page Footer

---

client/index.html

Fixes #175 
Removed the specified icon

Remove icon

---

client/index.html
package-lock.json

I had to remove discord from landing page .
Fixes #173

removed discord from landing page

---

client/index.html
client/styles.css

Fixes #170 
Pull request for the issue #170

Add Display Property in Footer issue#170

---

client/index.html
client/styles.css

Footer Changes
- Aligned position of the footer elements
- Aligned the icons
- Anchor tags were added
- Added Hover animation 
- Removed the weird left-border
Fixes #169

Footer change

---

client/app.js
client/index.html
client/styles.css

Dark mode added with Toggle button
I have made several changes in the files to incorporate the required changes.
Fixes #149 
Fixes #149
Contributing under JWOC.

Dark mode added with Toggle button

---

client/opensource_programs/index.html

A new Open source Program added in Season of Code ( SOC ) section.
Fixes #197

Issue 197 Fixed

---

client/styles.css

On toggle of dark mode button, top background is fixed
Refer screenshot: 
Fixes #216

Fix: Dark mode problem resolved

---

client/styles.css

Changed the font size of footer creator text from 10px to 16px.
Fixes #220

UI: Font Size of Creator Text Updated

---

client/index.html
client/styles.css

I have change the footer links font size as describe as in the issue.
Fixes #223

Change the font size of Footer Links issue223

---

client/index.html

Change the font size of footer header elements
UI Change
Fixes #224

fix: Change the font size of footer head elements

---

client/styles.css

Added a hovering effect feature to buttons in light theme

Added a hovering effect feature to buttons in light theme

---

client/opensource_programs/index.html
client/styles.css

Now , the mode is in light mode it shows the light theme and when the mode is in dark mode it shows the dark theme.
Fixes #229

Bug: Theme switched in the Dark mode and light mode Updated.

---

client/styles.css

Changed the font of social media logos to 23px
UI
Fixes #221

UI: Change font style of Social Links

---

client/Introduction-opensource/index.html
client/Introduction-opensource/style.css
client/beginner-friendly-repo/index.html
client/beginner-friendly-repo/style.css
client/git/git.css
client/git/index.html
client/index.html
client/opensource_programs/index.html
client/opensource_programs/style.css
client/styles.css

- [x ] Feature Request
resolved the issue 241 under jwoc 2024
Fixes #241
- [ x] The name of the resource is spelled correctly (if applicable)
- [ x] The link to the resource is working (if applicable)

hover addition in the footer and removed underline ;Thesri-issue241

---

client/styles.css

The hero section is now responsive. #233
Fixes #233

hero section

---

client/app.js
client/index.html
client/src/theme/theme_switch.css
client/styles.css

Fixes #244 
- Changed Theme Switch Button

theme-switch button fixed

---

client/app.js
client/index.html
client/styles.css

Fixed the Alignment of Theme Toggle Button
- Fixes #250

[ISSUE - 250] Alignment Issue with Dark and Light Mode Toggle in Responsive View (Below 800px)

---

client/Contributing to Opensource/index.html
client/Introduction-opensource/index.html
client/Introduction-opensource/style.css
client/beginner-friendly-repo/index.html
client/beginner-friendly-repo/style.css
client/faq/index.html
client/faq/style.css
client/git/git.css
client/git/index.html
client/opensource_programs/index.html
client/opensource_programs/style.css

Added scroll back to top button to all pages where it is not present
Fixes #265 
Please review my pull request

Added scroll back to top button to all pages

---

client/Contributing to Opensource/index.html
client/Introduction-opensource/index.html
client/beginner-friendly-repo/index.html
client/git/index.html
client/opensource_programs/index.html

Made required changes in files. Gave proper titles to the title bar of category pages.
Fixes #283

titlebar-fixed

---

client/styles.css

Made changes and the hamburger icon is visible only for the mobile view now.
Fixes #284

fixed-hamburger-visibility

---

client/Contributing to Opensource/index.html
client/Introduction-opensource/index.html
client/beginner-friendly-repo/index.html
client/faq/index.html
client/git/index.html
client/opensource_programs/index.html

I added favicon icon to all the pages where it is not present and also properly linked the navbar with pages of category section. And also i fixes the proper title of the page and i changed the navbar of category section pages properly .
I had fixes all these issues please review my pull request .
Fixes #281

#281 Favicon icon is not linked and the some pages are not linked with navbar

---

client/app.js
client/index.html
client/src/theme/theme_switch.css
client/src/theme/theme_switch.js
client/styles.css

Improved the dark mode.
Fixes #256

Improved dark mode

---

client/opensource_programs/index.html
client/opensource_programs/style.css

Fixed navbar of the open source program category page. 
Fixes #285 
Changed Navbar

navbar-fixed 

---

client/Contributing to Opensource/index.html

Remove Frequently Asked Questions from the contributing to open source page. Please check my pull request.
Fixes #309

Remove FAQ from the page

---

client/Contributing to Opensource/index.html
client/Introduction-opensource/index.html
client/beginner-friendly-repo/index.html
client/opensource_programs/index.html

I added dark & light toggle system to the every pages.
Fixes #301

Added Dark Mode to every pages

---

client/faq/index.html
client/index.html

Chore: Insert 'Frequently Asked Questions' in Landing Page Navbar #319 

---

client/opensource_programs/index.html
client/opensource_programs/style.css

I have made the webpage responsive for upto 300px screen width
Fixes #340

Made "Opensource Programs" webpage responsive

---

client/Introduction-opensource/style.css

Closes #339
I had fixed the responsiveness of the page , please check my pull request
Fixes #339

Fix the responsiveness of the page

---

client/Contributing to Opensource/index.html
client/Contributing to Opensource/style.css
client/Introduction-opensource/style.css

Update the UI of contributing to open source in the article section. Please review my pull request 
Fixes #350

Update the UI of contributing to open source

---

client/index.html

This pull request closes #347 , added Documentaion link to footer.
Fixes #347 
**working under JWOC**

Add documentation link to footer

---

client/styles.css

changed 'more' border color in dark mode

---

client/index.html

Successfully fixed the broken link.
- [/ ] Codebase
Fixes #346 
- [x ] The name of the resource is spelled correctly (if applicable)
- [x ] The link to the resource is working (if applicable)

Fixed the broken link

---

client/Introduction-opensource/index.html
client/Introduction-opensource/style.css

Update the UI of introduction to open source page. Please check my pull request.
Fixes #348

Update the UI of introduction to open source page

---

client/index.html
client/styles.css

Successfully created the link to faq page.
- [ x ] Codebase
Fixes #343 
- [ x ] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ x ] The name of the resource is spelled correctly (if applicable)
- [ x ] The link to the resource is working (if applicable)
- [ x ] The resource is added in the correct format (if applicable)
- [ x ] I have tested changes on my local computer (if applicable)

Fixed FAQ link

---

client/Introduction-opensource/index.html
client/Introduction-opensource/style.css

UI: Separate Resources Under 'Videos' in 'Introduction to Open Source' Page
changed the ui 
Fixes #349

UI: Separate Resources Under 'Videos' in 'Introduction to Open Source' Page

---

client/Contributing to Opensource/style.css
client/beginner-friendly-repo/style.css
client/git/git.css
client/opensource_programs/style.css

I had fixed the responsiveness of all the pages , please check my pull request .
Fixes #370

I had fixed the responsiveness of all the pages

---

client/Contributing to Opensource/style.css
client/Introduction-opensource/index.html
client/Introduction-opensource/style.css
client/git/git.css

Added hover effect on boxes and changed the video box of introduction to opensource , please check my pull request.
Fixes #372

Added hover effect and update the page introduction to opensource

---

client/pages/frequently-asked-questions/index.html

SVG link fixed 
Fixes #396
- [x ] The link to the resource is working (if applicable)

Chore: Fix SVG Link in 'Frequently Asked Questions' Page

---

client/pages/open-source-programs/index.html

I fixed the SVG link for the icon on the Open-Source-Programs-Page.
Fixes #395

Fixed SVG link in open-source-programs-page

---

client/components/footer.js

Solved issue #382 
Replaced 
> <a href="./Introduction-opensource/index.html" class="footer-links">Introduction to Open Source</a>
With
> <a href="./pages/introduction-to-open-source/index.html" class="footer-links">Introduction to Open Source</a>

Solved issue #382

---

client/app.js
client/components/footer.js
client/index.html
client/pages/beginner-friendly-repos/appBFR.js
client/pages/beginner-friendly-repos/index.html
client/pages/beginner-friendly-repos/styles.css
package.json
webpack.config.cjs

I have added the export function "darkTheme()" in a separate script called "appBFR". I also created another CSS class called "dark-theme-card" to customize the special style of the cards. Furthermore, I had to extend Index.html and beginner-friendly-repos.html and add a type="module" in the script to be able to use the export function. This also had to be added to the package.json.
The function is now executed in the app.json after the script has been worked through to avoid possible collisions of the style themes.
Fixes #407

UI: Improve Card UI in 'Beginner-Friendly Repos' Page

---

client/index.html

Fixed open source programs link

---

client/components/header.js

Made the logo in the navigation bar clickable.
Fixes #417

Chore: Add logo link to navbar

---

client/components/footer.js

I added a hover effect to "About" in Landing Page Footer
Fixes #421

[UI] Add hover effect to 'About' in Landing Page Footer

---

client/pages/open-source-programs/app.js
client/pages/open-source-programs/index.html
client/pages/open-source-programs/styles.css

Fixes #431 
- [x ] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide

converted open source program from static to dynamic

---

client/app.js
client/globals.css
client/index.html
client/styles.css
package-lock.json
package.json

The UI for the about and contribution card on the landing page has been improved and I reverted the changes made in the landing page hero container.
*Before*
*After*
Fixes #446

[Enhancement] - Improvement on about and contribution cards ui and reverted changes in Landing Page #451

---

client/components/footer.js
client/index.html

Updated path in footer and index file to fix navigation errors
Fixes #455

changed incorrect path pattern

---

README.md

Updated the GitHub - Get Started resource to the Learn Git and GitHub section in the ReadMe file.
Fixes #464

Updated the GitHub-Get Started Resource in README.md

---

README.md

Updated Four more Open Source Programs in README.
XROS Fellowship
Kharagpur Winter Of Code
NJACK Winter of Code
FOSS OverFlow
Fixes #466

Updated Four more Open Source programs in README.md

---

client/styles.css

Changed the hover color of category to its initial color in dark mode

---

client/styles.css

Responsive Hero Section in Home Page

---

README.md

Added the flutter repository in the Beginner Friendly Repositories Section in README.
Fixes #470

Added flutter into the Beginner-Friendly Repositories section in README.md

---

client/styles.css

Responsive Category Section 2

---

client/pages/learn-git-and-github/styles.css

Learn to Git and Github Page Responsive #476

---

client/pages/contributing-to-open-source/styles.css

Made Contributing to Open Source Page Responsive #475

---

client/styles.css

Aligned buttons in homepage (responsive)

---

client/pages/contributing-to-open-source/styles.css

Noramalised height of box1 and reduced font size pf headh2

---

client/pages/contributing-to-open-source/styles.css
client/pages/learn-git-and-github/styles.css

Noramalised height of box1 and scaled up hero section learn-git-and-github (responsive)

---

client/pages/beginner-friendly-repos/styles.css
client/pages/frequently-asked-questions/styles.css

Removed Streach of Hero in beginner Friendly Repo

---

client/pages/contributing-to-open-source/app.js

Dark mode for Contributing to Open Source Page 

---

client/pages/introduction-to-open-source/styles.css

Changed Hero Section in Introduction to open source(responsive)

---

client/pages/introduction-to-open-source/styles.css

Changed ui of box1 in introduction to open source

---

client/pages/introduction-to-open-source/styles.css

Changed Head Text to align in middle and increased font size in intoduction to open source

---

client/pages/open-source-programs/app.js

Dark mode for Open Source Programs Page

---

client/pages/introduction-to-open-source/styles.css
client/pages/open-source-programs/styles.css

Changed Hero section in open source programs

---

client/pages/open-source-programs/styles.css

Normalised card hide and added spacing in open source programs

---

client/pages/learn-git-and-github/index.html
client/pages/learn-git-and-github/styles.css
client/pages/open-source-programs/styles.css

Changed Hero in learn git and github

---

README.md

Added the requested resource by Black Duck to "Introduction to Open Source" in the README.md
Fixes #509

[Resource] Add a resource from Black Duck

---

client/pages/introduction-to-open-source/styles.css

Edited the slider navigation to fit dark mode.
Fixes #519

[UI] Adapt slider navigation in dark mode

---

README.md

An Introduction to Open Source Software Documentation

---

client/pages/contributing-to-open-source/app.js

Added dark mode on page contribution to open source.
Fixes #522

[UI] Add dark mode on contribution to open source

---

client/app.js
client/pages/contributing-to-open-source/app.js
client/pages/introduction-to-open-source/app.js
client/pages/learn-git-and-github/app.js
client/pages/open-source-programs/app.js

Fixed saving the dark/light theme toggle state on the main pages of the site. 
Fixes #524

[Codebase] Fix the state of Dark mode on pages

---

client/index.html
client/styles.css

FIX: Index Page HereComponent responsive fix

---

client/globals.css
client/pages/contributing-to-open-source/styles.css
client/pages/learn-git-and-github/styles.css
client/pages/open-source-programs/styles.css

Fixed white gap between body and footer on some pages. Also paid attention to dark mode.
Fixes #527

[UI] Fix white gap between body and footer

---

README.md
client/app.js
client/index.html
client/styles.css

This PR introduces a new "Rate Us" feature to encourage user feedback. Users can now click a "Rate Us" button.
This Rate Us Column appears in the center of the screen as soon as it past 30 seconds of surfing on the website. Ensures user input and interest of the user towards the website.
Fixes #544

Added a feature Rate Us.

---

README.md

Fix NJACK Winter of Code became CODEPEAK
Fixes #550

[Resource] Fix resource "NJACK Winter of Code" in README

---

.vscode/settings.json
client/pages/learn-git-and-github/app.js
client/pages/learn-git-and-github/index.html
client/pages/learn-git-and-github/styles.css

This pull request introduces a carousel to the Git & GitHub resources section using the Swiper library. The following changes were made to enhance the user experience and provide a clean, interactive way to navigate through the resources.
- Carousel Implementation: Integrated the Swiper library to create a responsive carousel for the resources section.
- Color Theme: Followed a consistent color theme for the carousel items to match the overall UI design of the page.
- Arrow Buttons and Pagination: Added neat and intuitive arrow buttons for navigation and implemented pagination for easy access to specific items within the carousel.
- Hover Effects and Animations: Enhanced user interaction by adding hover effects on carousel items and also included smooth animations to improve the overall …

[UI] Update Git Resources Section

---

client/globals.css
client/pages/learn-git-and-github/index.html
client/pages/learn-git-and-github/styles.css

https://github.com/user-attachments/assets/f6fea741-da49-4c58-b5d9-9660ff5a4436
Fixes #552

Fixes learn git and github page responsiveness
